// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj9ztKqXsOykY-X7iMsQgcL9WrNt7FK4M',
    appId: '1:121294545566:web:86f52ba70effa84d25518f',
    messagingSenderId: '121294545566',
    projectId: 'locationlogger-f8125',
    authDomain: 'locationlogger-f8125.firebaseapp.com',
    storageBucket: 'locationlogger-f8125.firebasestorage.app',
    measurementId: 'G-PPMVBDWCYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe6AfDwE7HHvC0WvJVZw8BuGI5BaRiUPg',
    appId: '1:121294545566:android:922a69ddd303132725518f',
    messagingSenderId: '121294545566',
    projectId: 'locationlogger-f8125',
    storageBucket: 'locationlogger-f8125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_NjL6RvZV_5Jca9-8rKyyuzOKV9gYGY',
    appId: '1:121294545566:ios:a0ddd5ed736298ad25518f',
    messagingSenderId: '121294545566',
    projectId: 'locationlogger-f8125',
    storageBucket: 'locationlogger-f8125.firebasestorage.app',
    iosBundleId: 'com.example.locationLogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB_NjL6RvZV_5Jca9-8rKyyuzOKV9gYGY',
    appId: '1:121294545566:ios:a0ddd5ed736298ad25518f',
    messagingSenderId: '121294545566',
    projectId: 'locationlogger-f8125',
    storageBucket: 'locationlogger-f8125.firebasestorage.app',
    iosBundleId: 'com.example.locationLogger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj9ztKqXsOykY-X7iMsQgcL9WrNt7FK4M',
    appId: '1:121294545566:web:779c793f5de0f8b225518f',
    messagingSenderId: '121294545566',
    projectId: 'locationlogger-f8125',
    authDomain: 'locationlogger-f8125.firebaseapp.com',
    storageBucket: 'locationlogger-f8125.firebasestorage.app',
    measurementId: 'G-8V76JD82EH',
  );
}
